### ISSUE TITLE
Error $sanitize:badparse in some buffers

### ISSUE THREAD

**Issue by vberger** [glowing-bear/glowing-bear#659]
When using both the version hosted at http://www.glowing-bear.org and the mobile application (newest version at this date), some buffers won't load any backlog.

In the webconsole, this error is logged:

```
Error: [$sanitize:badparse] http://errors.angularjs.org/1.3.14/$sanitize/badparse?p0=%3Ci32%2Ci32%3E%3B
M/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:6:417
F@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-sanitize.min.js:8:428
this.$get</<@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-sanitize.min.js:14:183
i/o@https://www.glowing-bear.org/min.js:2:17737
c@https://www.glowing-bear.org/min.js:1:30069
v/<@https://www.glowing-bear.org/min.js:2:186
v@https://www.glowing-bear.org/min.js:2:164
p/<@https://www.glowing-bear.org/min.js:2:4945
f/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:112:20
Pe/this.$get</l.prototype.$eval@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:125:301
Pe/this.$get</l.prototype.$digest@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:122:390
Pe/this.$get</l.prototype.$apply@https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:126:56
f@https://www.glowing-bear.org/min.js:2:12412
d/i.onmessage@https://www.glowing-bear.org/min.js:2:12545
```

I guess this is possibly linked to #480 ?

**Comment by lorenzhs** [comment]
Can you provide a sample input that triggers this? (you can copy it from console weechat).

It's likely another ngSanitize bug that we'll have to work around...

**Comment by vberger** [comment]
The message breaking in this case was the line:

```
playbot: let f = ::std::mem::transmute::<i32,i32>;
```

Apparently, it's the token `<i32,i32>;` that breaks things (it is what is contained in the forst line: `%3Ci32%2Ci32%3E%3B` ).

It also started tripping on content like `<pic.twitter.com/**********>` from my bitlbee_twitter buffer while before everything was ok. It started yesterday.

**Comment by lorenzhs** [comment]
I can't reproduce this, can you force-refresh Glowing Bear and see if it's still broken? (Ctrl+F5 usually)

**Comment by sophaskins** [comment]
:/ I'm still seeing this tonight - my stack trace is:
```
Error: [$sanitize:badparse] http://errors.angularjs.org/1.3.14/$sanitize/badparse?p0=%3Cobtuse%20questi…0actually%20be%20a%20(justified)%20question%20about%20correctness%3E%22%22
    at Error (native)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:6:417
    at F (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-sanitize.min.js:8:428)
    at h.module.provider.$get (http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-sanitize.min.js:14:183)
    at Object.e.service.o [as contentForMessage] (http://www.glowing-bear.org/min.js:2:17737)
    at c (http://www.glowing-bear.org/min.js:1:30085)
    at http://www.glowing-bear.org/min.js:2:186
    at Array.forEach (native)
    at Object.v [as handleLineInfo] (http://www.glowing-bear.org/min.js:2:166)
    at http://www.glowing-bear.org/min.js:2:4947(anonymous function) @ angular.js:11607b.$get @ angular.js:8557(anonymous function) @ angular.js:13197c.$get.l.$eval @ angular.js:14401c.$get.l.$digest @ angular.js:14217c.$get.l.$apply @ angular.js:14506f @ websockets.js:113r.onmessage.i.onmessage @ websockets.js:130
```
and the text itself of that line doesn't seem to have any particularly offensive characters:
```
<tychoish> the best part of all of it is he was like "lgtm modulo <obtuse question about a decision that turned out to actually be a (justified) question about correctness>""
```

**Comment by lorenzhs** [comment]
@sophaskins yeah, we haven't fixed `www.` yet, but https://latest.glowing-bear.org should be fixed. The problem is the `<>` characters, they trip angular's sanitizer.

**Comment by vberger** [comment]
Interestingly enough, it now works for me on `www.`. Did something change just now ? (it also works on `latest.` btw)

**Comment by lorenzhs** [comment]
Yeah, I updated `www.` a couple of minutes ago :) Closing this now, thanks for your help all!

**Comment by vberger** [comment]
However, I can still reproduce the bug using the android app, which has not been updated, I guess ?

**Comment by lorenzhs** [comment]
I just uploaded the new version, it'll take up to a few hours until the fixed version (0.5.2) shows up on all devices.

**Comment by sophaskins** [comment]
Thanks for fixing it so quickly! <3 Sorry about my confusion with latest >.>

**Comment by vberger** [comment]
Yes, everything is fixed now, including the android app. Thanks !
